# Generated by Django 3.2.12 on 2024-04-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('contato', models.CharField(max_length=11)),
                ('tipo_sanguineo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'Ab'), ('O', 'O')], max_length=2)),
                ('rh', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=8)),
                ('tipo_rh_corretos', models.BooleanField(default=False)),
                ('situacao', models.CharField(default='ATIVO', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('volume', models.FloatField()),
                ('situacao', models.CharField(max_length=7)),
                ('codigo_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doador')),
            ],
        ),
    ]
