# Generated by Django 3.2.12 on 2024-05-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='situacao',
            field=models.CharField(default='ATIVO', max_length=7),
        ),
    ]
